name       : perl-mozilla-ca
version    : 20180117
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/A/AB/ABH/Mozilla-CA-20180117.tar.gz : f2cc9fbe119f756313f321e0d9f1fac0859f8f154ac9d75b1a264c1afdf4e406
license    : MPL-2.0
component  : programming.perl
summary    : Mozilla::CA - Mozilla's CA cert bundle in PEM format
description: |
    Mozilla::CA provides a copy of Mozilla's bundle of Certificate Authority
    certificates in a form that can be consumed by modules and libraries
    based on OpenSSL.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
