name       : perl-mozilla-ca
version    : '20221114'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAARG/Mozilla-CA-20221114.tar.gz : 701bea67be670add5a102f9f8c879402b4983096b1cb0e20dd47d52d7a10666b
homepage   : https://metacpan.org/pod/Mozilla::CA
license    : MPL-2.0
component  : programming.perl
summary    : Mozilla::CA - Mozilla's CA cert bundle in PEM format
description: |
    Mozilla::CA provides a copy of Mozilla's bundle of Certificate Authority certificates in a form that can be consumed by modules and libraries based on OpenSSL.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
